trigger:
- main

pool:
  name: 'gpi'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Instalar Node.js'

- script: |
    npm install -g cloudcmd
  displayName: 'Instalar Cloudcmd'

- script: |
    cloudcmd
  displayName: 'Ejecutar Cloudcmd'
